import { GroceryCategory, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const CATEGORIES: GroceryCategory[] = [
  {
    id: '1',
    color: '#ffffba',
    label: 'Owoce',
    keywords: [
      'jabłko',
      'jabłka',
      'banan',
      'banany',
      'pomarańcza',
      'pomarańcze',
      'gruszka',
      'gruszki',
      'mandarynka',
      'mandarynki',
      'truskawka',
      'truskawki',
      'malina',
      'maliny',
      'śliwka',
      'śliwki',
      'winogrono',
      'winogrona',
      'ananas',
      'kiwi',
      'mango',
      'wiśnia',
      'wiśnie',
      'borówka',
      'borówki',
      'grejpfrut',
      'grejpfruty',
      'awokado',
      'brzoskwinia',
      'brzoskwinie',
      'nektarynka',
      'nektarynki',
      'granat',
      'melon',
      'cytryna',
      'cytryny',
      'limonka',
      'limonki',
      'aronia',
      'czereśnia',
      'czereśnie',
      'agrest',
      'jagoda',
      'jagody',
      'grapefrut',
      'grapefruty',
      'papaja',
      'daktyle',
      'figa',
      'figi',
      'kaki',
      'gujawa',
      'guawa',
      'mangostan',
      'nashi',
      'pomelo',
      'porzeczka',
      'porzeczki',
      'rokitnik',
      'żurawina',
      'kiwano',
      'kumkwat',
      'kokos',
      'marakuja',
      'liczi',
      'pitaja',
      'tamarillo',
      'tamarind',
      'uwikłane',
    ],
  },
  {
    color: '#baffc9',
    id: '2',
    label: 'Warzywa',
    keywords: [
      'ogórek',
      'ogórki',
      'marchew',
      'marchewka',
      'kapusta',
      'kapustka',
      'ziemniak',
      'ziemniaki',
      'pomidor',
      'pomidory',
      'pietruszka',
      'pietruszka',
      'seler',
      'selera',
      'rukola',
      'rukola',
      'szpinak',
      'szpinak',
      'kalafior',
      'kalafiory',
      'brokuł',
      'brokuły',
      'fasola',
      'fasolka',
      'bób',
      'por',
      'cebula',
      'cebule',
      'burak',
      'buraki',
      'sałata',
      'papryka',
      'papryki',
      'dynia',
      'dynie',
      'ziemniak',
      'ziemniaki',
    ],
  },
  {
    id: '3',
    color: '#ffdfba',
    label: 'Pieczywo',
    keywords: [
      'chleb',
      'bułki',
      'bułka',
      'bagietki',
      'bagietka',
      'pączki',
      'pączek',
      'rogale',
      'rogal',
      'chałka',
      'chałki',
      'ciabatta',
      'grzanki',
      'grzanka',
      'precelki',
      'precel',
      'pszenny',
      'pszenna',
      'żytni',
      'żytnia',
      'razowy',
      'razowa',
      'chrupki',
      'chrupka',
      'tosty',
      'tost',
      'buleczki',
      'buleczka',
      'kajzerki',
      'kajzerka',
      'placki',
      'placek',
      'francuski',
      'francuska',
      'ciastka',
      'ciastko',
    ],
  },
  {
    id: '4',
    color: '#c9c9ff',
    label: 'Słodycze',
    keywords: [
      'czekolady',
      'czekolada',
      'ciastka',
      'ciastko',
      'lizaki',
      'lizak',
      'czekoladki',
      'czekoladka',
      'batoniki',
      'batonik',
      'krówki',
      'krówka',
      'krakersy',
      'krakers',
      'czekoladowe',
      'drażetki',
      'drażetka',
      'praliny',
      'pralinka',
      'wafle',
      'wafel',
      'paluszki',
      'paluszek',
      'galaretki',
      'galaretka',
      'trufle',
      'trufel',
      'karmelki',
      'karmelek',
      'marcepany',
      'marcepan',
      'nugat',
      'nugat',
      'ciasteczka',
      'ciasteczko',
    ],
  },
  {
    id: '5',
    color: '#1b85b8',
    label: 'Produkty mleczne',
    keywords: [
      'mleko',
      'mleka',
      'ser',
      'sery',
      'jogurt',
      'jogurty',
      'kefir',
      'kefiry',
      'śmietana',
      'śmietany',
      'twaróg',
      'twarogi',
      'masło',
      'masła',
      'kwaśna śmietana',
      'kwaśne śmietany',
      'serki',
      'serków',
      'żółty ser',
      'żółte sery',
      'biały ser',
      'białe sery',
      'margaryna',
      'margaryny',
      'mleczko',
      'mleczka',
      'kakao',
      'serwatka',
      'serwatki',
      'kisiel',
      'kisiele',
      'serek',
      'serki',
      'śmietanka',
      'śmietanki',
      'mleczka',
      'mleczko',
      'serowy',
      'serowe',
    ],
  },
  {
    id: '6',
    color: '#c3cb71',
    label: 'Chemia',
    keywords: [
      'mydło',
      'mydła',
      'płyn do naczyń',
      'płyny do naczyń',
      'proszek do prania',
      'proszki do prania',
      'odświeżacz powietrza',
      'odświeżacze powietrza',
      'pasta do zębów',
      'pasty do zębów',
      'szampon',
      'szampony',
      'odplamiacz',
      'odplamiacze',
      'żel do prania',
      'żeły do prania',
      'płyn do czyszczenia',
      'płyny do czyszczenia',
      'płyn do kąpieli',
      'płyny do kąpieli',
      'gąbka',
      'gąbki',
      'środek czyszczący',
      'środki czyszczące',
      'balsam',
      'balsamy',
      'płyn do mycia',
      'płyny do mycia',
      'krem do rąk',
      'kremy do rąk',
      'żel pod prysznic',
      'żeły pod prysznic',
      'mop',
      'mopy',
    ],
  },
  {
    id: '7',
    color: '#ae5a41',
    label: 'Napoje i Alkohol',
    keywords: [
      'wódka',
      'wódki',
      'piwo',
      'piwa',
      'wino',
      'wina',
      'whisky',
      'whisky',
      'rum',
      'rumy',
      'tequila',
      'tequile',
      'likier',
      'likieru',
      'brandy',
      'brandy',
      'gin',
      'giny',
      'szampan',
      'szampany',
      'spirytus',
      'spirytusy',
      'cognac',
      'congacy',
      'martini',
      'martini',
      'szot',
      'szoty',
      'koniak',
      'koniaki',
      'absynt',
      'absynty',
      'wermut',
      'wermuty',
    ],
  },
  {
    id: '8',
    color: '#ffeb8e',
    label: 'Przekąski',
    keywords: [
      'chipsy',
      'chipsy',
      'orzechy',
      'popcorn',
      'paluszki',
      'prażynki',
      'prażynki',
      'pretzle',
      'pretzle',
      'chrupki',
      'chrupki',
      'orzeszki',
      'orzeszki',
      'ciastka',
      'ciasto',
      'ciasteczka',
      'kukurydza',
      'kukurydza',
      'krakersy',
      'krakersy',
      'precelki',
      'precle',
      'czipsy',
      'cipki',
    ],
  },
  {
    id: '9',
    color: '#fffbe7',
    label: 'Przyprawy',
    keywords: [
      'sól',
      'pieprz',
      'cynamon',
      'curry',
      'oregano',
      'bazylia',
      'papryka',
      'imbir',
      'majeranek',
      'kolendra',
      'koper',
      'kminek',
      'ziele angielskie',
      'przyprawa do kurczaka',
      'chili',
      'kardamon',
      'goździki',
      'anyż',
      'kurkuma',
      'kurry',
      'szafarnian',
    ],
  },
  {
    id: '10',
    color: '#88e5de',
    label: 'Inne',
    keywords: [
      'papier toaletowy',
      'świece',
      'baterie',
      'worki na śmieci',
      'gazeta',
      'długopis',
      'sznurek',
      'gumka',
      'zapałki',
      'spinacz',
      'pudełko',
      'chusteczki',
      'mydło',
      'szampon',
      'papier do pieczenia',
      'folia aluminiowa',
      'ocet',
      'woda utleniona',
      'patyczki do uszu',
      'gazetka',
    ],
  },
  {
    id: '11',
    color: '#e1abb5',
    label: 'Produkty Mięsne',
    keywords: [
      'piersi',
      'piersi',
      'mięso mielone',
      'wędliny',
      'szynki',
      'kiełbasa',
      'kiełbaski',
      'parówki',
      'wątróbka',
      'kurczak',
      'indyk',
      'polędwiczki',
      'korpus',
      'pasztet',
      'salami',
    ],
  },
];

const main = async () =>
  await prisma.groceryCategory.createMany({ data: CATEGORIES });

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
